name: Lint Code

on:
  workflow_call:

jobs:
  format:
    name: 'Format'
    runs-on: ubuntu-20.04

    steps:
      - name: Check format
        run: echo "docker run --rm my-org/my-repo:version run formats-checks"

  checks:
    name: 'Checks'
    runs-on: ubuntu-20.04

    steps:
      - name: Check code
        run: echo "docker run --rm my-org/my-repo:version run code-checks"

  security:
    name: 'Security'
    runs-on: ubuntu-20.04

    steps:
      - name: Check security
        run: echo "docker run --rm my-org/my-repo:version run security-checks"
